### ISSUE TITLE
Demo site not working

### ISSUE THREAD

**Issue by bcjonescbt** [googlecreativelab/aiexperiments-bird-sounds#3]
I've been checking 
   https://aiexperiments.withgoogle.com/bird-sounds/view/
for several days but it hasn't worked yet. I always see this message (from many computers, always in chrome)

![image](https://cloud.githubusercontent.com/assets/3099989/21060772/2acaada4-be17-11e6-92d8-58e6b1529e74.png)

**Comment by tambien** [comment]
uh oh. what version of Chrome are you running? I just tested on Chrome 55 and 57 and didn't see that error. I think that error is given if your browser doesn't support WebGL. Try [this](https://get.webgl.org/) link to see if your computer supports WebGL.

**Comment by bcjonescbt** [comment]
Running Chrome  54.0.2840.99 m, but you are correct - the WebGL test page you gave is showing it "disabled or unavailable" (on both machines I have here...). I'll have to figure that out (initial attempts have not worked). If you had a way to know it was WebGL, it might be a nice add to the error message.

**Comment by tambien** [comment]
good point. @mannytan let's consider being more specific with our error in this situation where the user is on Chrome, but does not have WebGL.
